### PR TITLE
fix travis

### PR DESCRIPTION
**Pull request by sideeffffect**
https://stackoverflow.com/questions/28751111/invalid-abi-armeabi-v7a-for-the-selected-target-with-google-apis

https://stackoverflow.com/questions/40710849/sys-img-armeabi-v7a-android-23-is-missing-from-the-repository

### CODE REVIEW

**Comment by sideeffffect** [comment]
It's now failing with

```bash
[info] [info] Compiling 3 Scala sources and 6 Java sources to /tmp/sbt_739e8f4/gen-android/target/scala-2.11/classes...
[info] [error] /tmp/sbt_739e8f4/gen-android/target/android/generated/source/org/scalaandroid/foo/TR.scala:47: type arguments [A] do not conform to method findViewById's type parameter bounds [V <: android.view.View]
[info] [error]   final def findView[A](tr: TypedResource[A]): A = findViewById[A](tr.id)
[info] [error]                                                                ^
[info] [error] one error found
```

@pfn any idea what could be going wrong?

**Comment by pfn** [comment]
The former error is a android sdk selection issue. Probably needs to be at least android-24 or something; I'm not sure what the latter error is caused by.

**Comment by sideeffffect** [comment]
@pfn I think I fixed the first issues with `android-24` and `findViewById`
but when I tried googling for the `annotations.xml` issue, I couldn't find almost anything, only hints that people solved it by upgrading to a newer versions of Gradle -- so that's what I'm trying now...

**Comment by sideeffffect** [comment]
let me reiterate from https://github.com/scala-android/sbt-android/pull/340#issue-319171339

> Thank you @jeffboutotte for this!!! pray your work on making CI work again gives `sbt-android` hope to come to life again
> we should merge this ASAP, to make other PRs possible
> @pfn do you think you could do that?

**Comment by sideeffffect** [comment]
@pfn we have a green build. can you please merge?

**Comment by Taig** [comment]
@sideeffffect I love to see you pushing this forward, but I don't want to merge a PR without @pfn's approval. Could you perhaps kick off a fork instead? It seems like @pfn is not maintaining this project actively anymore.

**Comment by pfn** [comment]
I'm trying to make some time to at least review and merge PRs if not
actively maintain; thanks for your patience.

**Comment by sideeffffect** [comment]
@Taig @dant3 guys would you be open to helping out @pfn with reviewing _and merging_ PR in the future?
there are some infrastructure changes that need to be done (like working CI, upgrading sbt to 1.x and so on) to keep this project alive, and the sooner that work gets merged the better

**Comment by pfn** [comment]
Thanks for your work @sideeffffect

**Pull request merged**
