### PR TITLE
Initial jack/jill support

### PR DESCRIPTION
**Pull request by dant3**
image

### CODE REVIEW

**Comment by pfn** [comment]
deleted what looks like spam

**Comment by bertderbecker** [comment]
Wow! Good work! Is it ready to use with Scala 2.12?

**Comment by pfn** [comment]
No, Jill does not support java 8, it is a glorified retrolambda at the moment.

**Comment by seroperson** [comment]
suddenly. jack toolchain was deprecated recently. seems like all of these features will be included in dx soon. 
https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html

**Comment by pfn** [comment]
Indeed, jack support will never be merged as a result.

**Pull request closed without merging**
